print("JJJJJ  W   W")
print("  J    W   W")
print("  J    W   W")
print("  J    W W W")
print("J J    WW WW")
print("J J    WW WW")
print(" JJ    W   W")

print("      *     *                    ")
print("                      *          ")
print("*         *                 *    ")
print("     *           *     *         ")
print("           HHHHHHH        *      ")
print(" *         HHHHHHH               ")
print("     *   HHHHHHHHHHH    *     *  ")
print("         *   @ @   *             ")
print("        *     ^     *            ")
print("  *       *       *         *    ")
print("         SSS * * S               ")
print("         * SSSSSSSS *            ")
print("       *      O   SS  *          ")
print("      *       O    S   *         ")
print("      *       O        *         ")
print("       *              *          ")
print("           *   *   *             ")